import pexpect
child = pexpect.spawn('lldb ./sic')
child.expect('\(lldb\)')
child.sendline('run')
child.expect('Sic 1.1 by Claudio')
child.sendline('position startpos')
child.sendline('go depth 12')
child.expect('stop reason = EXC_BAD_ACCESS')
child.sendline('bt')
child.expect('\(lldb\)')
print(child.before.decode())
child.sendline('frame select 0')
child.expect('\(lldb\)')
print(child.before.decode())
child.sendline('p pos')
child.expect('\(lldb\)')
print(child.before.decode())
